name: pytorch
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.7
  - ipykernel
  - jupyter
  - matplotlib
  - pip
  - pytorch 
  - torchvision 
  - torchaudio 
  - cudatoolkit=11.1
  - sklearn-pandas